title: Raphael Cervantes
description: Physicist postdoc looking for dark matter and other physics beyond the Standard Model
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
